name: Hello World Schedule

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  hello_word:
    runs-on: unbuntu@latest
    steps:
      - name: Echo Current Time
        run: echo "The current server time is ${date}"

